GMantenimiento/Innova.GMantenimiento.MVC/Models/OrdenCompra.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Innova.GMantenimiento.MVC.Models
{
    public class OrdenCompra
    {
        public int CodOrdCompra { get; set; }
        [DataType(DataType.Date)]
        public DateTime FechaEmision { get; set; }
        [DataType(DataType.Date)]
        public DateTime FechaEntrega { get; set; }
        public string CodEstado { get; set; }
        public string Moneda { get; set; }
        public decimal TipCambio { get; set; }
        public int CodEmpleado { get; set; }
        public int CodCotizacion { get; set; }
        public int CodProveedor { get; set; }
        public int CodArticulo { get; set; }
        public decimal? Cantidad { get; set; }
        public decimal? PreUnitario { get; set; }
        public decimal? Descuento { get; set; }

        public decimal? Total { get; set; }
    }
}

GMantenimiento/Innova.GMantenimiento.MVC/Controllers/OrdenCompraController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Innova.GMantenimiento.MVC.Models;
using Innova.Common.Core.Entities;
using Innova.GMantenimiento.Domain;

namespace Innova.GMantenimiento.MVC.Controllers
{
    public class OrdenCompraController : Controller
    {
        // GET: OrdenCompra
        public ActionResult RegistrarCompra(List<OrdenCompra> entidad, string FechaEmision, string FechaEntrega, string CodProveedor, string CodEstado, string Moneda, string TipoCambio, string CodEmpleado, string CodCotizacion)
        {
            List<tb_OrdCompraDet> listadet = new List<tb_OrdCompraDet>();
            decimal total = 0;
            foreach (var item in entidad)
            {
                listadet.Add(new tb_OrdCompraDet()
                {
                    CodArticulo = item.CodArticulo,
                    Cantidad = item.Cantidad,
                    PreUnitario = item.PreUnitario,
                    Descuento = item.Descuento,
                });
                total = Convert.ToDecimal(((item.PreUnitario * item.Descuento) / 100) * item.Cantidad);
            }

            tb_OrdCompra ordencompra = new tb_OrdCompra()
            {
                FechaEmision = Convert.ToDateTime(FechaEmision),
                FechaEntrega = Convert.ToDateTime(FechaEntrega),
                CodEstado = CodEstado,
                Moneda = Moneda,
                TipCambio = Convert.ToDecimal(TipoCambio),
                CodEmpleado = Convert.ToInt32(CodEmpleado),
                CodCotizacion = Convert.ToInt32(CodCotizacion),
                CodProveedor = Convert.ToInt32(CodProveedor),
                Total = total
            };



            new BL_TransaccionOrdenCompra().TransaccionCompra(ordencompra, listadet);
            return RedirectToAction("ListaOrden");
        }

        public ActionResult ListaOrden()
        {
            List<tb_OrdCompra> lista = new BL_OrdenCompra().listarodencompra().Where(x => x.CodEstado != "2").ToList(); ;
            List<OrdenCompra> entidad = new List<OrdenCompra>();
            foreach (var item in lista)
            {
                entidad.Add(new OrdenCompra()
                {
                    CodOrdCompra = item.CodOrdCompra,
                    FechaEmision = item.FechaEmision,
                    FechaEntrega = item.FechaEntrega,
                    CodEstado = item.CodEstado,
                    Moneda = item.Moneda,
                    TipCambio = item.TipCambio,
                    CodEmpleado = item.CodEmpleado,
                    CodCotizacion = item.CodCotizacion,
                    CodProveedor = item.CodProveedor,
                    Total = item.Total
                });
            }
            return View(entidad);
        }
        [HttpPost]
        public ActionResult ListaOrden(string codigo)
        {
            if (codigo != string.Empty)
            {
                List<tb_OrdCompra> lista = new BL_OrdenCompra().listarodencompra().Where(x => x.CodOrdCompra == Convert.ToInt32(codigo) && x.CodEstado != "2").ToList();
                List<OrdenCompra> entidad = new List<OrdenCompra>();
                foreach (var item in lista)
                {
                    entidad.Add(new OrdenCompra()
                    {
                        CodOrdCompra = item.CodOrdCompra,
                        FechaEmision = item.FechaEmision,
                        FechaEntrega = item.FechaEntrega,
                        CodEstado = item.CodEstado,
                        Moneda = item.Moneda,
                        TipCambio = item.TipCambio,
                        CodEmpleado = item.CodEmpleado,
                        CodCotizacion = item.CodCotizacion,
                        CodProveedor = item.CodProveedor,
                        Total = item.Total
                    });
                }
                return View(entidad);
            }
            else
            {
                List<tb_OrdCompra> lista = new BL_OrdenCompra().listarodencompra().Where(x => x.CodEstado != "2").ToList();
                List<OrdenCompra> entidad = new List<OrdenCompra>();
                foreach (var item in lista)
                {
                    entidad.Add(new OrdenCompra()
                    {
                        CodOrdCompra = item.CodOrdCompra,
                        FechaEmision = item.FechaEmision,
                        FechaEntrega = item.FechaEntrega,
                        CodEstado = item.CodEstado,
                        Moneda = item.Moneda,
                        TipCambio = item.TipCambio,
                        CodEmpleado = item.CodEmpleado,
                        CodCotizacion = item.CodCotizacion,
                        CodProveedor = item.CodProveedor,
                        Total = item.Total
                    });
                }
                return View(entidad);
            }
        }

        public ActionResult AnularOrdenCompra(int codigo)
        {
            new BL_OrdenCompra().AnularCompra(codigo);
            return RedirectToAction("ListaOrden");
        }


    }
}

GMantenimiento/Innova.GMantenimiento.MVC/Views/OrdenCompra/ListaOrden.cshtml
@model IEnumerable<Innova.GMantenimiento.MVC.Models.OrdenCompra>

@{
    ViewBag.Title = "ListaOrden";
}

<br />
<br />
@using (Html.BeginForm("ListaOrden", "OrdenCompra", FormMethod.Post))
{
    <div row>
        <div class="col-md-10 col-lg-offset-1">
            <input type="text" name="codigo" />
            <input type="submit" value="Buscar" />
        </div>
    </div>
}

<div class="row">
    <div class="col-md-10 col-lg-offset-1">
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.CodOrdCompra)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.FechaEmision)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.FechaEntrega)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CodEstado)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Moneda)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.TipCambio)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CodEmpleado)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Total)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.CodOrdCompra)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FechaEmision)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FechaEntrega)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CodEstado)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Moneda)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TipCambio)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CodEmpleado)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Total)
                    </td>
                    <td>
                        @Html.ActionLink("Anular Orden", "AnularOrdenCompra", new { codigo = item.CodOrdCompra })
                    </td>
                </tr>
            }

        </table>
    </div>
</div>