GMantenimiento/Innova.GMantenimiento.Web.Mvc/Controllers/ArticuloesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GMSTp2.DataModel;

namespace GMSTp2.WebSite.Controllers
{
    public class ArticuloesController : Controller
    {
        private GMSData db = new GMSData();

        // GET: Articuloes
        public ActionResult Index()
        {
            return View(db.Articulo.ToList());
        }

        public IEnumerable<SelectListItem> Combo()
        {
            var data_list = db.Articulo
                        .Select(x =>
                                new SelectListItem
                                {
                                    Value = x.CodArticulo.ToString(),
                                    Text = x.NomArticulo
                                });

            return new SelectList(data_list, "Value", "Text");
        }

        public Articulo  Obtener(int? codigo) {
            return db.Articulo.Where(f => f.CodArticulo == codigo).FirstOrDefault();
        }

        // GET: Articuloes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Articulo articulo = db.Articulo.Find(id);
            if (articulo == null)
            {
                return HttpNotFound();
            }
            return View(articulo);
        }

        // GET: Articuloes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Articuloes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CodArticulo,NomArticulo,UnidMedida,Modelo,Observacion")] Articulo articulo)
        {
            if (ModelState.IsValid)
            {
                db.Articulo.Add(articulo);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(articulo);
        }

        // GET: Articuloes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Articulo articulo = db.Articulo.Find(id);
            if (articulo == null)
            {
                return HttpNotFound();
            }
            return View(articulo);
        }

        // POST: Articuloes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CodArticulo,NomArticulo,UnidMedida,Modelo,Observacion")] Articulo articulo)
        {
            if (ModelState.IsValid)
            {
                db.Entry(articulo).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(articulo);
        }

        // GET: Articuloes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Articulo articulo = db.Articulo.Find(id);
            if (articulo == null)
            {
                return HttpNotFound();
            }
            return View(articulo);
        }

        // POST: Articuloes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Articulo articulo = db.Articulo.Find(id);
            db.Articulo.Remove(articulo);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }



    }
}

GMantenimiento/Innova.GMantenimiento.Web.Mvc/Controllers/InstalacionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GMSTp2.DataModel;

namespace GMSTp2.WebSite.Controllers
{
    public class InstalacionsController : Controller
    {
        private GMSData db = new GMSData();

        // GET: Instalacions
        public ActionResult Index()
        {
            return View(db.Instalacion.ToList());
        }

        public IEnumerable<SelectListItem> Combo()
        {
            var data_list = db.Instalacion
                        .Select(x =>
                                new SelectListItem
                                {
                                    Value = x.CodInstalacion.ToString(),
                                    Text = x.NomInstalacion
                                });

            return new SelectList(data_list, "Value", "Text");
        }

        public Instalacion Obtener(int? codigo)
        {
            return db.Instalacion.Where(f => f.CodInstalacion == codigo).FirstOrDefault();
        }

        // GET: Instalacions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Instalacion instalacion = db.Instalacion.Find(id);
            if (instalacion == null)
            {
                return HttpNotFound();
            }
            return View(instalacion);
        }

        // GET: Instalacions/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Instalacions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CodInstalacion,NomInstalacion,AbrevInstalacion,Aforo")] Instalacion instalacion)
        {
            if (ModelState.IsValid)
            {
                db.Instalacion.Add(instalacion);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(instalacion);
        }

        // GET: Instalacions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Instalacion instalacion = db.Instalacion.Find(id);
            if (instalacion == null)
            {
                return HttpNotFound();
            }
            return View(instalacion);
        }

        // POST: Instalacions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CodInstalacion,NomInstalacion,AbrevInstalacion,Aforo")] Instalacion instalacion)
        {
            if (ModelState.IsValid)
            {
                db.Entry(instalacion).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(instalacion);
        }

        // GET: Instalacions/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Instalacion instalacion = db.Instalacion.Find(id);
            if (instalacion == null)
            {
                return HttpNotFound();
            }
            return View(instalacion);
        }

        // POST: Instalacions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Instalacion instalacion = db.Instalacion.Find(id);
            db.Instalacion.Remove(instalacion);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GMantenimiento/Innova.GMantenimiento.Web.Mvc/Controllers/TareaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GMSTp2.DataModel;
using GMSTp2.WebSite;

namespace GMSTp2.WebSite.Controllers
{
    public class TareaController : Controller
    {
        private GMSData db = new GMSData();


        //metodo que previene la existencia de una entidad con los mismos atributos
        private bool exists(Tarea tarea) {
            bool existe = false;

            var x = db.Tarea.Where(t => t.NomTarea == tarea.NomTarea || t.AbrevTarea == tarea.AbrevTarea).FirstOrDefault();
            if (x != null)
                existe = true;

            return existe;
        }

        public IEnumerable<SelectListItem> Combo()
        {
            var data_list = db.Tarea
                        .Select(x =>
                                new SelectListItem
                                {
                                    Value = x.CodTarea.ToString(),
                                    Text = x.NomTarea
                                });

            return new SelectList(data_list, "Value", "Text");
        }


        public Tarea Obtener(int? codigo)
        {
            return db.Tarea.Where(f => f.CodTarea == codigo).FirstOrDefault();
        }

        // GET: Tarea 
        public ActionResult Index(string valor)
        {
            List<Tarea> t = new List<Tarea>();
            if (valor != null)
                t = db.Tarea.Where(fx => fx.NomTarea.Contains(valor)).ToList();
            else
                t = db.Tarea.ToList();

            utils.EventLogger.EscribirLog("Inicia Vista > Tarea");

            return View(t);
        }


        public ActionResult ReporteListadoTarea() {

            utils.PDFExport pdf = new utils.PDFExport();
            utils.DataUtils datautils = new utils.DataUtils();
            System.Data.DataTable dtbdatos = new DataTable();
            System.Data.DataSet dst = new DataSet();
            dtbdatos.TableName = "Tareas";
            dtbdatos = datautils.ToDataTable<Tarea>(db.Tarea.ToList());
            dst.Tables.Add(dtbdatos);
            string filename = pdf.SavePDF(dst,"Listado de Tareas",null);
            return File(filename, "application/pdf", Server.UrlEncode(filename));
        }

        // GET: Tarea/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tarea tarea = db.Tarea.Find(id);
            if (tarea == null)
            {
                return HttpNotFound();
            }
            return View(tarea);
        }

        // GET: Tarea/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Tarea/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CodTarea,NomTarea,AbrevTarea")] Tarea tarea)
        {
            if (ModelState.IsValid)
            {
                if (exists(tarea)==false)
                {
                    db.Tarea.Add(tarea);
                    db.SaveChanges();
                }
                return RedirectToAction("Index");
            }

            return View(tarea);
        }

        // GET: Tarea/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tarea tarea = db.Tarea.Find(id);
            if (tarea == null)
            {
                return HttpNotFound();
            }
            return View(tarea);
        }

        // POST: Tarea/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CodTarea,NomTarea,AbrevTarea")] Tarea tarea)
        {
            if (ModelState.IsValid)
            {
                if (exists(tarea) == false)
                {
                    db.Entry(tarea).State = EntityState.Modified;
                    db.SaveChanges();
                }
                return RedirectToAction("Index");
            }
            return View(tarea);
        }

        // GET: Tarea/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tarea tarea = db.Tarea.Find(id);
            if (tarea == null)
            {
                return HttpNotFound();
            }
            return View(tarea);
        }

        // POST: Tarea/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Tarea tarea = db.Tarea.Find(id);
            db.Tarea.Remove(tarea);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GMantenimiento/Innova.GMantenimiento.Web.Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    <title>.:: @ViewBag.Title - Innova Schools ::.</title>
    <link href="../Content/css/style.css" rel="stylesheet" type="text/css" />
    <link href="../Content/css/skin.css" rel="stylesheet" type="text/css" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)  
</head>
<body class="skin-gym bar-white">
    <section class="wrap-ui">
        <!--<header>-->
        <header class="header">
            <div class="pull-left">
                <div class="logo-data">
                    <img src="../Content/images/system/innova_schools-logo.png" width="90px" />
                </div>
            </div>
            <div class="pull-right">
                <div class="pull-left comp-btn-user">
                    <button id="btnGroupDrop2" type="button" class="btn">
                        <span class="ico-user"></span>
                        <span class="name">@TempData["viewbag_username"]</span>
                    </button>
                </div>
                <div class="pull-left">
                    <a href="#" class="btn-salir"></a>
                </div>
            </div>
        </header>
        <!--</header>-->
        <!-- nav -->
        <div class="menu">
            <a class="btn-show"></a>
            <a class="logo" href="#">
                <img src="../Content/images/system/innova_schools-logo.png" alt="Logo">
            </a>
            <nav class="nav">
                @Html.Partial("_MenuGMS")
            </nav>
        </div>
        <!-- cierra nav -->
        <!--<wrap-content>-->
        <div class="wrap-content">
            <!--</main-aside>-->
            <!--<pull-main-content>-->
            <div class="pull-main-content">
                <!--<main-content>-->
                <div class="main-content view-wrap">
                    @RenderBody()
                </div>
                <!--</main-content>-->
                <div class="footer">
                    <strong>&copy; Proyecto Academico UPC </strong> 
                </div>
            </div>
            <!--</pull-main-content>-->
        </div>
        <!--</wrap-content>-->
        <div class="up-page upPage"><span class="glyphicon glyphicon-chevron-up"></span></div>
    </section>
    <!--JS-->
    <script type="text/javascript" src="../Scripts/bootstrap-jquery-ui/js/bootstrap.js"></script>
    <script type="text/javascript" src="../Scripts/app/jquery.mCustomScrollbar.js"></script>
    <script type="text/javascript" src="../Scripts/app/common.js"></script>
    <script type="text/javascript">
        $(function () {
            $('[data-toggle="tooltip"]').tooltip();
            generales();
            removeMenuPanel();
        });

         

    </script>
</body>
</html>

GMantenimiento/Innova.GMantenimiento.Web.Mvc/Views/Shared/_MenuGMS.cshtml
<ul class="nav-wrap">
    <li class="nav-01">
        <span class="list-collapse">Sistemas <i class="ico-collapse"></i></span>
        <ul class="nav-collapse">
            <li class="nav-02">
                <a href="#" class="nav_ajx">Gestión Directiva</a>
            </li>
            <li class="nav-02">
                <a href="#" class="nav_ajx">Gestión de Adquisiciones</a>
            </li>   
        </ul>
    </li>
    <li class="nav-01">
        <span class="list-collapse">Gestión de Mantenimiento <i class="ico-collapse"></i></span>
        <ul class="nav-collapse">
            <li class="nav-02">
                <a href="#">Operaciones</a>
                <ul class="nav-collapse-sub">
                    <li class="nav-03">@Html.ActionLink("Generar Planner", "Index", "Planner_mantenimiento")</li>
                    <li class="nav-03">@Html.ActionLink("Control Calidad", "Index", "Calidad_mantenimiento")</li>
                </ul>
            </li>
            <li class="nav-02">
                <a href="#">Mantenimiento</a>
                <ul class="nav-collapse-sub">
                    <li class="nav-03">@Html.ActionLink("Tareas ", "Index", "Tarea")</li>
                    <li class="nav-03">@Html.ActionLink("Instalaciones", "Index", "Instalacions")</li>
                    <li class="nav-03">@Html.ActionLink("Materiales", "Index", "Articuloes")</li>
                    <li class="nav-03">@Html.ActionLink("Periodo Académico", "Index", "Periodo_Academico")</li>
                </ul>
            </li> 
        </ul>
    </li>
    <li class="nav-01">
        <span class="list-collapse">[POR DEFINIR] <i class="ico-collapse"></i></span>
        <ul class="nav-collapse">
            <li class="nav-02">
                <a href="#">[POR DEFINIR]</a>
                <ul class="nav-collapse-sub">
                    <li class="nav-03"><a href="#">[POR DEFINIR]</a></li>
                    <li class="nav-03"><a href="#">[POR DEFINIR]</a></li>
                </ul>
            </li>
            <li class="nav-02">
                <a href="#">[POR DEFINIR]</a>
                <ul class="nav-collapse-sub">
                    <li class="nav-03"><a href="#">Diego</a></li>
                    <li class="nav-03"><a href="#">Diego</a></li>
                </ul>
            </li>
            <li class="nav-02">
                <a href="#">[POR DEFINIR]</a>
                <ul class="nav-collapse-sub">
                    <li class="nav-03"><a href="#">[POR DEFINIR]</a></li>
                    <li class="nav-03"><a href="#">[POR DEFINIR]</a></li>
                </ul>
            </li>
        </ul>
    </li>
    <li class="nav-01">
        <span class="list-collapse">[POR DEFINIR] <i class="ico-collapse"></i></span>
        <ul class="nav-collapse">
            <li class="nav-02">
                <a href="#">[POR DEFINIR]</a>
                <ul class="nav-collapse-sub">
                    <li class="nav-03"><a href="#">[POR DEFINIR]</a></li>
                    <li class="nav-03"><a href="#">[POR DEFINIR]</a></li>
                </ul>
            </li>
            <li class="nav-02">
                <a href="#">[POR DEFINIR]</a>
                <ul class="nav-collapse-sub">
                    <li class="nav-03"><a href="#">Diego</a></li>
                    <li class="nav-03"><a href="#">Diego</a></li>
                </ul>
            </li>
            <li class="nav-02">
                <a href="#">[POR DEFINIR]</a>
                <ul class="nav-collapse-sub">
                    <li class="nav-03"><a href="#">[POR DEFINIR]</a></li>
                    <li class="nav-03"><a href="#">[POR DEFINIR]</a></li>
                </ul>
            </li>
        </ul>
    </li>
    <li class="nav-01">
        <span class="list-collapse">[POR DEFINIR] <i class="ico-collapse"></i></span>
        <ul class="nav-collapse">
            <li class="nav-02">
                <a href="#">[POR DEFINIR]</a>
                <ul class="nav-collapse-sub">
                    <li class="nav-03"><a href="#">[POR DEFINIR]</a></li>
                    <li class="nav-03"><a href="#">[POR DEFINIR]</a></li>
                </ul>
            </li>
            <li class="nav-02">
                <a href="#">[POR DEFINIR]</a>
                <ul class="nav-collapse-sub">
                    <li class="nav-03"><a href="#">[POR DEFINIR]</a></li>
                    <li class="nav-03"><a href="#">[POR DEFINIR]</a></li>
                </ul>
            </li>
            <li class="nav-02">
                <a href="#">[POR DEFINIR]</a>
                <ul class="nav-collapse-sub">
                    <li class="nav-03"><a href="#">[POR DEFINIR]</a></li>
                    <li class="nav-03"><a href="#">[POR DEFINIR]</a></li>
                </ul>
            </li>
        </ul>
    </li>
    <li class="nav-01">
        <span class="list-collapse">[POR DEFINIR] <i class="ico-collapse"></i></span>
        <ul class="nav-collapse">
            <li class="nav-02">
                <a href="#">[POR DEFINIR]</a>
                <ul class="nav-collapse-sub">
                    <li class="nav-03"><a href="#">[POR DEFINIR]</a></li>
                    <li class="nav-03"><a href="#">[POR DEFINIR]</a></li>
                </ul>
            </li>
            <li class="nav-02">
                <a href="#">[POR DEFINIR]</a>
                <ul class="nav-collapse-sub">
                    <li class="nav-03"><a href="#">Diego</a></li>
                    <li class="nav-03"><a href="#">Diego</a></li>
                </ul>
            </li>
            <li class="nav-02">
                <a href="#">[POR DEFINIR]</a>
                <ul class="nav-collapse-sub">
                    <li class="nav-03"><a href="#">[POR DEFINIR]</a></li>
                    <li class="nav-03"><a href="#">[POR DEFINIR]</a></li>
                </ul>
            </li>
        </ul>
    </li>
    <li class="nav-01">
        <span class="list-collapse">Seguridad <i class="ico-collapse"></i></span>
        <ul class="nav-collapse">
            <li class="nav-02">
                <a href="#">[POR DEFINIR]</a>
                <ul class="nav-collapse-sub">
                    <li class="nav-03"><a href="#">[POR DEFINIR]</a></li>
                    <li class="nav-03"><a href="#">[POR DEFINIR]</a></li>
                </ul>
            </li>
            <li class="nav-02">
                <a href="#">[POR DEFINIR]</a>
                <ul class="nav-collapse-sub">
                    <li class="nav-03"><a href="#">Diego</a></li>
                    <li class="nav-03"><a href="#">Diego</a></li>
                </ul>
            </li>
            <li class="nav-02">
                <a href="#">[POR DEFINIR]</a>
                <ul class="nav-collapse-sub">
                    <li class="nav-03"><a href="#">[POR DEFINIR]</a></li>
                    <li class="nav-03"><a href="#">[POR DEFINIR]</a></li>
                </ul>
            </li>
        </ul>
    </li>
</ul>